In [4]:
def jaccard_coef(x ,y ):
  x = list(x.split())
  y= list(y.split())
  intersection = len(list(set(x).intersection(y)))
  union = (len(x) + len(y)) - intersection
  return float(intersection) / union
ref = 'meet me at the airport tomorrow'
test = 'meat me at the aeroport 2morrw'
print("Jaccard Coefficient =" , jaccard_coef(ref , test))

Jaccard Coefficient = 0.3333333333333333


In [5]:
def edit_distance(s1, s2):
    m=len(s1)+1
    n=len(s2)+1

    tbl = {}
    for i in range(m): tbl[i,0]=i
    for j in range(n): tbl[0,j]=j
    for i in range(1, m):
        for j in range(1, n):
            cost = 0 if s1[i-1] == s2[j-1] else 1
            tbl[i,j] = min(tbl[i, j-1]+1, tbl[i-1, j]+1, tbl[i-1, j-1]+cost)

    return (tbl[i,j])

ref = 'meet me at the airport tomorrow'
test = 'meat me at the aeroport 2morrw'
ref = ref.split()
test = test.split()
print("Length of ref" , len(ref))
summ=0
for i in range(0 , 6):
  dist = edit_distance(ref[i] , test[i])
  print("Edit Distance of word" , i ,'=' , dist)
  summ = summ + dist
print("total correction =" , summ)
print("Average Correction Words= " , summ/len(ref))

Length of ref 6
Edit Distance of word 0 = 1
Edit Distance of word 1 = 0
Edit Distance of word 2 = 0
Edit Distance of word 3 = 0
Edit Distance of word 4 = 2
Edit Distance of word 5 = 3
total correction = 6
Average Correction Words=  1.0


In [6]:
# Cosine Similarity

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk.corpus import stopwords
import numpy as np
import numpy.linalg as LA
import nltk
nltk.download('stopwords')

train_set = ["The sky is blue.", "The sun is bright."]  # Documents
test_set = ["The sun in the sky is bright."]  # Query
stopWords = stopwords.words('english')

vectorizer = CountVectorizer(stop_words = stopWords)
#print vectorizer
transformer = TfidfTransformer()
#print transformer

trainVectorizerArray = vectorizer.fit_transform(train_set).toarray()
testVectorizerArray = vectorizer.transform(test_set).toarray()
print ('Fit Vectorizer to train set', trainVectorizerArray)
print ('Transform Vectorizer to test set', testVectorizerArray)

transformer.fit(trainVectorizerArray)
print (transformer.transform(trainVectorizerArray).toarray())

transformer.fit(testVectorizerArray)
tfidf = transformer.transform(testVectorizerArray)
print(tfidf.todense())

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mande\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


Fit Vectorizer to train set [[1 0 1 0]
 [0 1 0 1]]
Transform Vectorizer to test set [[0 1 1 1]]
[[0.70710678 0.         0.70710678 0.        ]
 [0.         0.70710678 0.         0.70710678]]
[[0.         0.57735027 0.57735027 0.57735027]]
